### ISSUE TITLE
Crash on 1.3.0-alpha under Android

### ISSUE THREAD

**Issue by Framstag** [janbar/osmin#1]
Pixel 3 with current Android. Installation and download of germany map works. Map rendering works also selection of POI works. However as soon as I enter an explicit text to search for a location (for example "Gelsenkirchen" with is a city in germany ut also "Bla" which should only have non-excact matches) the waiting swirl appears, in case of "Bla" even possible matches appear but then the application crashes.

**Comment by janbar** [comment]
@Framstag , yep I reproduced the issue with the germany map. It is related to https://github.com/Framstag/libosmscout/pull/1014 . But seems it is not fully fixed. I am working on it ...

**Comment by Framstag** [comment]
I have tested the new version. Search now works (similar to the libosmscout demos). Thanks for the fix!
 
You can close the issue.

**Comment by janbar** [comment]
Great
