### ISSUE TITLE
Building on arm64 PinePhonePro

### ISSUE THREAD

**Issue by magdesign** [janbar/osmin#20]
Trying to build on PinePhonePro as described in the readme (UNIX) to get latest version.

However, when doing:

`cmake -B build -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .`

getting following error:
```
CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_C_COMPILER:

    /usr/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:4 (project):
  The CMAKE_CXX_COMPILER:

    /usr/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.
```
Anyone a hint on how to build on manjaro arm64 devices (or how to tell CMake where to find the compiler)?!

**Comment by magdesign** [comment]
Sorry, I figured it out about the clang:

```
sudo pacman -S clang

sudo pacman -S base-devel
```

but still not able to build, any instructions would be brilliant ;-)

**Comment by janbar** [comment]
Could you post the output of the build with clang ?

**Comment by magdesign** [comment]
After rebooting the device and doing a `sudo pacman -Syyu` it seems to build:

https://gist.github.com/magdesign/11badc273c08f510f5433970a651c01d

but how would I run, respectively install it now?

**Comment by magdesign** [comment]
It worked as expected,
now on version 1.8.2 on PinePhonePro.
Seems to be more stable for routing....

Thanks for your great work, would love to donate paypal? patreon? or writing docs?

**Comment by janbar** [comment]
Wep, writing docs ...

I released 1.8.3 today to fix GPS permissions on Android. Maybe work well with pinePhone.

**Comment by magdesign** [comment]
Works well on Pinephonepro, will test it in the wild soon to get used to it...
there are some annoying UI issues when using the OS in darktheme.

Can write some docs, only for Linux devices (no android or ios available in my world :-)
Will try compiling on UBports now... ;-)

**Comment by janbar** [comment]
Does it need a desktop file on PinePhone to startup ?

**Comment by magdesign** [comment]
In KDE/Manjaro it creates a desktop file after doing `sudo make install` and a reboot:
![image20220408_191938749](https://user-images.githubusercontent.com/5273166/162492255-e8478c41-b289-4ac8-ad57-f89b6a89358e.jpg)

When starting from Terminal with: `osmin`
it looks like this:
![image20220408_192713617](https://user-images.githubusercontent.com/5273166/162492418-5fef0b3c-9e82-4484-89fb-fdabea2dadff.jpg)
(no fullscreen, but good for debugging)

With system "Breeze Dark" theme, the font looks like behind a grey wall:
![image20220408_190658947](https://user-images.githubusercontent.com/5273166/162492753-94387e30-e844-44c6-b86b-dd9f5401d69e.jpg)

But with the "Breeze Classic" it looks good:
![image20220408_192019012](https://user-images.githubusercontent.com/5273166/162492910-a0692e51-829e-4d1c-9803-a020be69d01c.jpg)

**Comment by janbar** [comment]
Look good !
With the system "Breeze Dark" theme, you should change the app setting style to "dark".
There is something weird about the theme style. Normally I forced the style to "Material" to avoid these issues. But seems I missed something if the system set its own style. The style "Material" look like that on all platforms:

![image](https://user-images.githubusercontent.com/2353635/162563112-0ab0cfd3-2b7d-4eb7-95fa-ba9cc4364048.png)

I will check that ...

**Comment by janbar** [comment]
Also , there are dedicated behaviors on "mobile" devices, specially to save the battery when the app is in the background. But actually those behaviors are enabled when the flag "Android" is set to true ... ;-) . So I could add a new flag to handle that, i.e "DeviceType = Mobile | Desktop". The flag is static at compile time.

**Comment by janbar** [comment]
I added the commit 78674dc781a6e28c476c4a2bdeab48703c11389f to force the style "Material" at the first startup.
But now for your device, you have to change it manually in the app config file. The file path is `$HOME/.config/io.github.janbar/osmin.conf`, and you have to change the parameter `style` to the value `Material`. That will resolve the theme issue.

**Comment by magdesign** [comment]
> I added the commit [78674dc](https://github.com/janbar/osmin/commit/78674dc781a6e28c476c4a2bdeab48703c11389f) to force the style "Material" at the first startup. But now for your device, you have to change it manually in the app config file. The file path is `$HOME/.config/io.github.janbar/osmin.conf`, and you have to change the parameter `style` to the value `Material`. That will resolve the theme issue.

That does not help, since everytime I open OSMIN it overrides the `style` in `osmin.conf` with: `org.kde.breeze`

Also switching in app to "dark" does not make any difference.
maybe recompiling after commit 78674dc will help (I will try).

**Comment by magdesign** [comment]
> Also , there are dedicated behaviors on "mobile" devices, specially to save the battery when the app is in the background. But actually those behaviors are enabled when the flag "Android" is set to true ... ;-) . So I could add a new flag to handle that, i.e "DeviceType = Mobile | Desktop". The flag is static at compile time.

This sounds like a great idea!
However, we currently have a broken sleep/wakeup state on PinePhonePro and I can not really test this, but would make sense to add the flag anyway.

**Comment by janbar** [comment]
The commit bff25d1b4ea3051e08672fba227827ff7a191c64 introduce the cmake flag "BUILD_DEVICE_MOBILE" to enable behavior for mobile device.

`cmake ... -DBUILD_MOBILE_DEVICE=ON ...`

**Comment by magdesign** [comment]
As a reference for anyone wants to
# Build on PostmarketOS

Keep in mind that on **linuxmobile** you need to manually enable GPS and Geoclue. See [here](https://wiki.postmarketos.org/wiki/User:Magdesign#GPS). I recommend you to also build and configure an actual [ModemManager](https://wiki.postmarketos.org/wiki/User:Magdesign#ModemManager) version.


Install dependencies:

```
sudo apk update
sudo apk upgrade -a
sudo apk add git cmake clang g++ build-base qt5-qtbase qt5-qtbase-x11 qt5-qtsvg-dev qt5-qtmultimedia-dev openmp-dev qt5-qtquickcontrols2-dev qt5-qtsensors-dev qt5-qtremoteobjects-dev

```

Cloning and building:
```
git clone https://github.com/janbar/osmin.git

cd osmin
git submodule init
git submodule update --force
mkdir build

cmake -B build -DBUILD_DEVICE_MOBILE=ON -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ .

cmake --build build/ -j$(nproc)

sudo cmake --build build/ --target install

```

voila, you have a recent version of the fantastic osmin navugation application on your linuxphone.
