### ISSUE TITLE
Tracking => Reset statistics does not work

### ISSUE THREAD

**Issue by magdesign** [janbar/osmin#24]
Under Tracking, the Reset statistics button does not do anything, to reset the statistics I have to re-open the app.
(PinePhonePro, Manjaro).
This is no big deal, just wanted to mention... ;-)
![tracking_statistics](https://user-images.githubusercontent.com/5273166/163175279-d5a0de94-8e51-4837-88ca-83a43a452c8f.png)

**Comment by janbar** [comment]
Ah that is weird. It works here. I will check it.
When the tracker is recording, the statistics cannot be cleared. But in your preview the button is enabled and so the tracker doesn't record. Maybe the callback has been discarded ...

**Comment by janbar** [comment]
good catch. while the device position doesn't change, the data aren't signaled changed.
