### ISSUE TITLE
Search UI workflow

### ISSUE THREAD

**Issue by Framstag** [janbar/osmin#3]
It look like I can use the search only to start routing.

Question:
* Start search via main screen
* Enter a location
* I get the small map below with the location in focus
* I can now close the small map window or select "Go" or mark it as favorit
* If I select "Go" UI is switched to a routing dialog with in turn show the route afterwards
* I miss the option to close the small small and show the selected location in the big map

Do I miss something or is this a missing feature?

**Comment by janbar** [comment]
This is a missing feature. We have to add an other button in the small map to simply show the place in the big map.

**Comment by Framstag** [comment]
OK. I suggest to use github labels to mark the issue as enhancement ;-) Of course I would be interested in an implemention :-)

**Comment by janbar** [comment]
Right now for next release.
In small map (favorite or search pages): A new button "Target"
<img width="240" alt="Capture d’écran 2021-04-06 à 23 37 33" src="https://user-images.githubusercontent.com/2353635/113781930-b6bd8f00-9731-11eb-81e9-4bec4c548afc.png">
Clicking the button, the page is popped and the big map show the position with the information box. You can always click "Go" or "Add to favorites" from the big map.
<img width="379" alt="Capture d’écran 2021-04-06 à 23 38 57" src="https://user-images.githubusercontent.com/2353635/113782267-3ba8a880-9732-11eb-9a5e-ae9fea59d46c.png">

**Comment by janbar** [comment]
Released in 1.5.0
