### ISSUE TITLE
Enhancement: shelter

### ISSUE THREAD

**Issue by magdesign** [janbar/osmin#33]
Currently traveling with osmin and I love it, due bad weather I'd love to find [shelters](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshelter) fast and easy. In the search category or as a map overlay. 

Please add if possible.
big thanks!

**Comment by Karry** [comment]
Hi. It makes sense to me. But whole process will take some time. I created merge request for upstream project: https://github.com/Framstag/libosmscout/pull/1298 I am using different import definition, but keeping it in sync with upstream one. When it will be merged, next map database imports will contain this type `amenity_shelter` (in October). Then @janbar may add shelter to some stylesheet (outdoor I guess) and to search...

**Comment by magdesign** [comment]
Thanks. this sounds great! 
until then i will contribute shelters and drinking water places to osm, there are many here in the woods in france :)

**Comment by magdesign** [comment]
any news on this?
i made a short video about using osmin and the workaround to mark shelters:

https://odysee.com/@sharinggoodmoments:2/linuxmobile:4

would be nice to have them in osmin

**Comment by janbar** [comment]
still todo

**Comment by janbar** [comment]
include in release 1.12.5

**Comment by janbar** [comment]
Include in release 1.12.5

**Comment by janbar** [comment]
How to search for Shelter ? Like that ...
![Capture d’écran du 2024-09-02 09-49-19](https://github.com/user-attachments/assets/0dc7a9eb-2ecf-47ff-81bf-3b162745bbc2)

**Comment by magdesign** [comment]
this is amazing, thank you so much!
