### ISSUE TITLE
Purpose of the question mark main view element

### ISSUE THREAD

**Issue by Framstag** [janbar/osmin#4]
The main map view has a !question mark" button below the menu button. What is its purpose?

**Comment by janbar** [comment]
From the last merge in libosmscout, I made a typo in my code changing the name for the new function "setVehicileScaleFactor". That breaks the map initializer of the app, and this button has no effect. I made the fix and now I push the new version ... 1.3.2-alpha

So this button is to move the map on the current position to show where you are.

**Comment by janbar** [comment]
I pushed the new release 1.3.2-alpha including the APK. Now you will see again the green dot of your current position. Clicking the "?" will center the map on the current position.

**Comment by Framstag** [comment]
Ah, OK. I have the feeling the icon is not optimal regarding the intention. But the feature works now, you can close the issue.

**Comment by janbar** [comment]
I updated the icon of the button to be more explicite ;-).
