### ISSUE TITLE
cannot backup tracks on windows due to filename semicolon

### ISSUE THREAD

**Issue by fusionneur** [janbar/osmin#46]
windows fs does not allow semicolon (:)
tracks are saved under (eg.) \Internal shared storage\Android\data\io.github.janbar.osmin\files\GPX
file name contains semicolon: 2022-04-24T20:54:02.gpx 

trying to transfer files on windows fails

filename shouldn't contain semicolon

**Comment by janbar** [comment]
Will be fixed

**Comment by janbar** [comment]
Yep, only new files. You to rename the farmers.

**Comment by janbar** [comment]
On the tracks screen, you should have a burger menu on the right of each track. Press it then you will see an item to rename the file.
