### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by GreenLunar** [janbar/osmin#49]
This is a fine bavigation software that actually fits my needs, including list (step-by-step aka "storyline") mode.

I suggest to publish OSMIN at F-Droid store.

_I don't use Android, I'm using OSMIN on postmarketOS._

**Comment by greghab** [comment]
Just a note: it is available through the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/io.github.janbar.osmin) F-Droid repo.

**Comment by greghab** [comment]
I would say so. I'm not a maintainer, but I think that adding a note under the android part of the readme section documenting to use that repo, would probably suffice. Assuming that publishing in the official fdroid repo is not a current priority. So using that additional repo is good-enough for now.

**Comment by GreenLunar** [comment]
What should we do with this ticket?

Should we close it, even though it is technically valid?

**Comment by greghab** [comment]
I would personally create a PR, which inserts a bullet at the bottom of the android part of the readme section, with the following statement: 
- For F-Droid users, osmin is currently available unofficially through the [IzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/io.github.janbar.osmin) repo.

Unless you're packaging it on F-Droid yourself, you can't make them, so the main thing you can do is just ask what they think about it, and get their input/feedback on it. So create a PR adding the unofficial repo to the readme per above, and then inquire further in the PR description about official packaging through F-Droid, and whether they want to do it. That seems like a good step for moving this forward. It may be that they do not like unofficial F-Droid repos published on the projects readme, so I don't know. I would just do a PR and see, and go from there, and wait for further comment/review from someone.

**Comment by greghab** [comment]
Last comment on this:
- There's also https://github.com/ImranR98/Obtainium, which lets you install directly from a git source. You can install osmin through its "Search GitHub" feature, and app updates work through it. It's not F-Droid, but I guess it solves the "[trusted party problem](https://privsec.dev/posts/android/f-droid-security-issues/)". But F-Droid is still probably nice to have, especially for discoverability.

**Comment by GreenLunar** [comment]
Does osmin compile in accord with the following policy?

https://f-droid.org/docs/Inclusion_Policy/

**Comment by GreenLunar** [comment]
For your information https://gitlab.com/fdroid/rfp/-/issues/2541

**Comment by janbar** [comment]
Hi, osmin is fully open sources and it hasn't any external proprietary dependencies.
Dependencies are:
* libosmscout (https://github.com/Framstag/libosmscout)
* openssl, zlib , libxml2, libiconv, marisa (all internally build from sources)
* Qt framework: Qt5Widgets Qt5Xml Qt5Svg Qt5Network Qt5Sensors Qt5Multimedia Qt5RemoteObjects Qt5Positioning
Finally the java bootstrap sources are included in the source tree, and the build could be done by anybody.

APKs provided in the release section are signed with my own certificate, and therefore this guarantees the origin of the binary package provided.

**Comment by licaon-kter** [comment]
Just a FYI, one needs to also built QT before building the app, hence the recipe is not something that's easy to do without devs familiar with the app.

@GreenLunar I'm closing the RFP as there has not been any activity since then
