### ISSUE TITLE
Highlight selection in Map Downloads

### ISSUE THREAD

**Issue by omnivagant** [janbar/osmin#54]
On a screen wider than that of a handheld device in portrait mode the download button, to the right, is far apart from the country name, to the left, so that it is hard to see what button to press in order to download the desired map.

Hovering over the download button highlights it, one idea could be to also highlight the country name at the same time.

Other ideas could be lines in between or that every second country has a background of a darker shade.

**Comment by janbar** [comment]
fixed in commit 7df0299fac0f323e0a5b8afb8fa0175bad445ea5
