### ISSUE TITLE
Enhancement: Voice direction during routing

### ISSUE THREAD

**Issue by Framstag** [janbar/osmin#6]
I was able to test routing functionality for a car ride today.

(I also use this ticket for some positive feedback ;-))

* Location was around 20-30 Km away
* Routing calculation was very fast 
* I left the recommended route twice (know neuralgic points in the route where there are close alternatives). Detection of "we left the route" and recalculation of the new route were fast, too
* Overall experience was already very goof

Please add voice navigation hints. AFAIK there are already same basic for this, likely only Android integration is missing?

**Comment by janbar** [comment]
Good news it works great for you. I passed lot of time to tune the routing in real world. That is also the reason of the PR I proposed to merge in the lib.
Enabling voices is in my todo. Same thing I want to test it in real conditions before push the change and keep a user experience as best as possible.

**Comment by janbar** [comment]
I tested voice successfully. Still to add a page for settings ...

**Comment by janbar** [comment]
The feature has been merged the the development branch https://github.com/janbar/osmin/tree/dev/20210323 .

**Comment by janbar** [comment]
Once latest libosmscout commits are pulled in my fork , I will make the new alpha release 1.3.3-alpha.

**Comment by Framstag** [comment]
* Downloaded and installed
* Configuration of voice done (if you start a route without a voice configure it would be nice to see a hint at least once)
* Started route, first voice command triggered
* Will test later on current day, since I have s small distance to drive, will call back via new issue, if there is an obvious problem/improvement. If not, everything is fine :-)
