### ISSUE TITLE
Will not display maps

### ISSUE THREAD

**Issue by AndyM48** [janbar/osmin#61]
I tried to upgraded osmin from 1.9.7 to master and the maps were not displayed.

So I downloaded the maps again, this appeared to succeed but finished with
```
Basemap found and loaded from ' "/home/andrew/osmin/resources/world" '...
qml: checking updates for map British Isles (europe,britain-and-ireland)
qml: map time: Sat Sept 23 03:32:00 2023 GMT+0200 latestReleaseTime: Sat Sept 23 03:32:00 2023 GMT+0200 (object)
qml: Application state changed to active
qml: Application state changed to suspended
~PlaneMapRenderer
~MapRenderer
~Router
~NavigationModule
~ServiceFrontend
Signal handler is destroyed.
```
(I have attached the logs from the upgrade in case they are of any help: [logfile](https://github.com/janbar/osmin/files/13009064/Upgrade_Log.txt)

Then I restarted osmin, still no maps displayed. The errors were:
```
Signal handler is enabled.
User locale setting is C
using file ':/i18n/osmin_en.qm' for translations.
Checking installed assets...
Found assets version 1.9.7
Resource directory is /home/andrew/osmin/resources
Trying to connect to service ...
Loading online tile providers from  "/home/andrew/osmin/resources/online-tile-providers.json"
Loading providers from  "/home/andrew/osmin/resources/map-providers.json"
Loading providers from  "/home/andrew/osmin/resources/voice-providers.json"
MapManager ctor
42,9 Warning: Unknown way type 'highway_motorway'
```
followed by multiple  `Warning: Unknown way type` messages

It seems that I did something wrong but I am not sure what?

**Comment by janbar** [comment]
The message `Found assets version 1.9.7` means you are running osmin 1.9.7 and not master (1.10.4). So the map version downloaded with "master" is incompatible with 1.9.7.

**Comment by AndyM48** [comment]
Got it. When I ran osmin from the build directory it said:
```
Found assets version 1.9.7
Trying to connect to service ...
**Assets will be upgraded to version 1.10.4**
Connect to service succeeded
```
So I assumed that osmin had been upgraded. Which proves what they say about assume :)

Sorry to have bothered you.

**Comment by janbar** [comment]
Osmin required its assets which must be installed with the binary (see the folder .../share/osmin/). Obviously assets content depends of the osmin version. If you install manually a new binary of osmin, then you have to copy the new assets too. Typing `make install` will do the job ... Mixing old assets (1.9.7) with new binary (1.10.4) could cause some issues/warnings etc

**Comment by AndyM48** [comment]
I know that this is blindingly obvious when you point it out.

Would you consider updating the README to make it clear that this should be the final step, and not:

> Finally build it to make the target binary osmin
> 
> cmake --build build/ -j8
>

**Comment by AndyM48** [comment]
I don't think that you have provided a .desktop file for *nix systems?
