### ISSUE TITLE
missing map ?

### ISSUE THREAD

**Issue by v3rtux** [janbar/osmin#64]
Sorry but I'm unable to find Reunion island map. Where to download ?
Thanks a lot !!

**Comment by Karry** [comment]
Hi, I am using OpenStreetMap extracts made by Geofabric as source of OSM Scout imports. Regions on the server follows the same hierarchy as Geofabric... So, you may find Reunion island under [France regions](http://download.geofabrik.de/europe/france.html).

**Comment by v3rtux** [comment]
Sorry for this, I was looking for it under "Africa" ...
Thanks a lot for the quick answer, and keep up the nice work with this sleek app !!
