### ISSUE TITLE
Configuring location of files

### ISSUE THREAD

**Issue by sjehuda** [janbar/osmin#67]
First matter:

Instead of using ~/Maps/ and ~/osmin/, I suggest to use ~/.local/share/ (i.e. "data" directory) for Maps, Voices and other data.

Second matter:

I am testing (I actually use it) osmin on computer (Arch Linux) and on mobile (postmarketOS), Arch Linux sets the location of maps under ~/osmin/maps/ while postmarketOS sets it at ~/Maps.

I use Syncthing to synchronize data, including of OSMIN which causes to unnecessary duplications.

Conclusion:

Making the data organized and configurable would be good.

**Comment by PureTryOut** [comment]
Partially a duplicate of https://github.com/janbar/osmin/issues/41

**Comment by sjehuda** [comment]
Bart, shall we close this ticket?

**Comment by PureTryOut** [comment]
If you think your requests are fully covered by that issue then sure.

Also it's weird to have people call me Bart when my display name is clearly different :see_no_evil:

**Comment by sjehuda** [comment]
PureTryOut, I beg your pardon.

I will close this ticket and once #41 is implemented, I will test osmin again against pmOS.

Closing.
