### ISSUE TITLE
[Bug] Statistics calculate jumps 

### ISSUE THREAD

**Issue by magdesign** [janbar/osmin#74]
sometimes there are weird numbers in Tracking Statistics. This is caused when I open osmin and my phone needs a few minutes to get gps. Then it jumps to the actual location with lightspeed, see screenshot:
![osmin-speed](https://github.com/user-attachments/assets/955749f6-803c-44db-a856-6cf933b43544)

**Comment by janbar** [comment]
It should be fixed from 1.13 or the latest 1.12. I added a new algo to compute velocity and so discard data when G is greater than 1.

**Comment by magdesign** [comment]
thanks.
