### ISSUE TITLE
https://janbar.github.io/osmin/ results in 404

### ISSUE THREAD

**Issue by 1Maxnet1** [janbar/osmin#76]
The website seems to be not available anymore. Any plans to bring it back? Otherwise I think a bunch of links in the appstream data need to be removed/replaced.

**Comment by janbar** [comment]
The links should be removed, because never existed.

**Available links are:**
https://github.com/janbar/osmin/wiki
https://github.com/janbar/osmin/issues
https://github.com/janbar/osmin
